---
title: "gather"
author: "Winona Guo"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinythemes)
library(tidyverse)
library(janitor)
library(readr)
library(readxl)

```


```{r final project}
# Shiny Tools
# https://shiny.rstudio.com/reference/shiny/1.5.0/
# https://shiny.rstudio.com/tutorial/ 


# My datasets: 
  
#1) Imperial Roots of Global Trade 
# https://www.wnvermeulen.com/empires/
# view(empires)

#2) Measuring the Impacts of Colonialism: A New Data Set for the Countries of Africa and Asia
# https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/UQZFYA
# view(colonialism)

#3) countries vulnerable to climate
# https://www.cgdev.org/publication/dataset-vulnerability-climate-change
#view(vulnerability)

#4) per country co2 emissions
# https://github.com/datasets/co2-fossil-by-nation
#view(emissions)

# Wyatt sent this answer key from week 3 of class which explains the below.
# https://github.com/wyatthurt/gov-50-class-scripts/blob/main/class-2020-09-22/week_3_A.Rmd


colonialism <- read_xls("shiny_app/raw_data/colonialism.xls") %>%
  clean_names() 

vulnerability <- read_xls("shiny_app/raw_data/vulnerability.xls", skip = 2) %>%
  clean_names() %>%
  rename(vulnerable = climate_vulnerability_cv_cdi_adj_for_income_regulation)
view(vulnerability)


```

``` {r Creating plots for pg 2}

q1 <- colonialism %>%
  select(country_name, colyears) 
    
q2 <- vulnerability %>%
  select(country, vulnerable, world_sub_region)

q3 <- inner_join(q1, q2, by = c("country_name" = "country")) 


graph1 <- q3 %>%
  ggplot(aes(x = colyears, y = vulnerable, color = world_sub_region)) +
  geom_point(alpha = 0.7) +
  labs(title = "Countries by Years Colonized and Vulnerability to Climate Risk",
       x = "Years Colonized",
       y = "Vulnerability to Climate Risk",
       caption = "This graph indicates there is not a significant correlation
       overall between the years a country has been colonized, 
       and its current vulnerability to climate risk.") +
  theme_bw() + 
  scale_color_discrete("World Region")
  

graph1

# Other code—delete at end.
# filter(country_name %in% c("Somalia", "China", "Angola")) 
    
```